### ISSUE TITLE
Switch two lights independent

### ISSUE THREAD

**Issue by hans-peter123** [KhaosT/HAP-NodeJS#106]
Hallo, 
I have 2 lights in the MyTouchHome app. Now when I say: Turn on the light, both lights switched. How can I make this independent, so that I have to say exactly: Turn the Desk lamp on? And normaly only the other lamp going to be switched?
Thanks for your help

**Comment by connyg** [comment]
You can use the room name and the device name in your voice command. It's a bit tricky, though, you need to experiment with device name you give and which voice command Siri understands. Took me a while to find out.

Am 24.07.2015 um 23:54 schrieb hans-peter123 <notifications@github.com<mailto:notifications@github.com>>:


Hallo,
I have 2 lights in the MyTouchHome app. Now when I say: Turn on the light, both lights switched. How can I make this independent, so that I have to say exactly: Turn the Desk lamp on? And normaly only the other lamp going to be switched?
Thanks for your help

**Comment by KhaosT** [comment]
@hans-peter123 Siri currently only recognizes Service name (not the accessory name). If you want to do that, please rename the light service on accessories to "Desk Lamp" and "Other Light". By doing so, when you say turn on Desk Lamp, Siri will only turn on the Desk Lamp.
