### ISSUE TITLE
Unreachable after stopping and restarting HAP-NodeJS

### ISSUE THREAD

**Issue by cflurin** [KhaosT/HAP-NodeJS#108]
Hi,
I've installed HAP-NodeJS on a Mac mini (OS X 10.10.4) and I'm using the EVE App on my iPhone 6 (iOS 8.4). The example BridgeCore.js works fine, however after restarting BridgeCore.js EVE shows the message "unreachable". In order to reactivate the communication I've to restart (power off/on) my iPhone.

**Comment by justme-1968** [comment]
this is probably due to some sockets sill in TIME_WAIT state. visible with netstat. but i haven't found what the reason is.

**Comment by cflurin** [comment]
Connecting the iOS device with Mac mini using the build in Wifi instead of the Router Wifi solves the problem.

**Comment by nfarina** [comment]
You know I was actually starting to be suspicious of your wifi network :) The way that iOS leaves the connection open forever seemingly without any "keepalive" type of packets seems very strange to me. What kind of router do you have?

**Comment by cflurin** [comment]
Actually the iPhone is still connected to "Router" but the Mac mini was only connected via Ethernet Cable. I turned on additionally the Wifi on the Mac mini. Now I've two connections (Ethernet and Wifi). And this seems to be the solutions.
My LAN consists of a Cablemodem with router properties (Ethernet and Wifi) and an additional access point (one Network).

**Comment by nfarina** [comment]
OK cool. You might close the issue for now since you have a workaround and it seems related to the network configuration (unless you can think of anything HAP-NodeJS could do to help with this situation)

**Comment by nzhome** [comment]
that does pose an interesting question though..  why does bonjour *not* work across his Ethernet. but it does across his wifi.  I bet his web browser and dns is working fine. the WHOLE point of bonjour is to ensure this sort of problem does not exist.    that means that hap-nodejs  has still got a bug somewhere here.    It is a pity we can't get in and debug some of these cases properly.. cflurin here has painstakingly gone through a lot of effort to achieve a workaround, or just by chance he got it working because it resets a number of connections doing it that way.  I don't like seeing issues like this just closed so easily.  it will come back again I'm sure.

**Comment by nzhome** [comment]
@SphtKr just mentioned a change to the "username" in app.js so it looks like a new device.

**Comment by cflurin** [comment]
Another setting that improves stability (at least with OS X): 

    supportBonjour = true,

**Comment by SphtKr** [comment]
@nzhome Really answering this is obviously going to be impossible and out of scope...however I can give you an example from my own experience:

I set up a few older routers with DD-WRT and tried to make wireless bridges out of them. Eventually I got everything to work great--except Bonjour. Turned out, the way DD-WRT treated the two "sides" (wired and wireless) of the device were as two separate networks with the same subnet, and routed all traffic belonging to that subnet between the "two" networks. Problem was, Bonjour uses a special address (224.0.0.251) that wasn't in my bridged subnet (192.168.n.1/24)...so the packets never crossed. To make it work you have to manually install and set up a `mdnsForwarder` process in the custom firmware!

Google around for that and you'll find it's not always as simple as you'd think...though in the vast majority of cases it "just works". There's a whole Cisco deployment guide about making it work right in complex networks. I also had an odd case myself where my use of Powerline networking bridges were causing several gremlins in my network, including Bonjour problems.

So, I wouldn't necessarily say that there's still a Bonjour related bug in HAP-nodeJS...and if there were, it'd probably be in the `mdns` package anyway. Possible that it's local, but unlikely.

**Comment by nzhome** [comment]
@SphtKr  I agree entirely with your comments, and thank you for sharing that info, i learnt a little more about bonjour.   I guess what I'm saying is that we will never know because it wasn't debugged.   he has no bridging, and his subnet is full. why would a router not broadcast packets between ethernet and wifi.  I have never seen a router not allow broadcasting, and I have tested over 50 models of wifi routers for 255.255.255.255 broadcasting between ethernet and wifi. I think it was just coincidence, time will tell for sure.  I too still have a lot to learn about bonjour, I am no expert on this.

**Comment by snowdd1** [comment]
Multicast on addresses 224.0.x.y IS NOT Broadcasting. Some routers support broadcasting (required for such plain things as dhcp) but have no or insufficient support for multicasting. 
Years back I had the issue when AirPlay came to us - one of the access points did not forward the multicasts properly and needed replacement.

**Comment by cflurin** [comment]
What is the purpose of supportBonjour? Almost all examples have set:

    supportBonjour: false

Off Topic:

I'm trying to connect EVE or Inseon+ with the Homekit Accessory Simulator, V1.0 (38)
but I've got the message:
> Out of Order
> the request device does not conform to Homekit specifications

**Comment by KhaosT** [comment]
@cflurin Please download the latest HomeKit Accessory Simulator 1.3 (74) from [here](https://developer.apple.com/downloads/)

**Comment by cflurin** [comment]
@KhaosT OK, Thanks, I did it for my Xcode 6.4 but obviously I got always the same old version.
now I've downloaded  "Hardware_IO_Tools_for_Xcode_7_beta_5"  >  version 1.3 (73).
