### ISSUE TITLE
Accessory Disabled Automatically Even The Server Is Running...

### ISSUE THREAD

**Issue by apple13developer** [KhaosT/HAP-NodeJS#138]

**Comment by ak0815** [comment]
Same problem

**Comment by KhaosT** [comment]
not exactly sure why this happened but according to some people who encountered similar problem, this might be a compatibility issue with mDNS and your router.

**Comment by futuretec** [comment]
Hey there,
same problem here!
I didn't have the time yet to debug this properly - all I can say, that I experienced the same issues when i was "going live" with my application.
I developed my garage door opener on a Raspberry Pi while being connected to the home network (internet connectivity, routing by a "powerful" Netgear device, no issues!)
Now I installed the system on location and It works once .. but then no more. (dedicated WiFi network, no internet access, attached to a "cheap" TP-Link TL-WR702N Nano-Router)

TP-Link states in a troubleshooting document, that to support Apple Bonjour/mDNS you have to enable
=> Multicast = IGMPv2
=> IGMP snoop

**Comment by justme-1968** [comment]
i had bad experience with these igmp snoop features on small consumer routers. the routers should be as dumb as possible and not interfere. try not to use them and waste a little bandwidth instead. it is more reliable.

**Comment by sjschneider** [comment]
I have the same problem running this on a Raspberry Pi over WiFi connected to an Apple Time Capsule (router).  Everything works for 20 minutes or so and then it becomes grayed out in the HMCatalog app on my iPhone.  How would I find out if this is an mDNS compatibility issue with my router?

**Comment by futuretec** [comment]
@sjschneider This sounds odd. As long as the avahi-deamon (mDNS/Bonjour) is up and running on your RaspberryPi and you didn't mess up the network configuration you should be fine. It is absolutely unlikely, that your router (Apple's own TimeCapsule) wouldn't support Bonjour.

I would suggest you check your avahi setup (zeroconf) or the log files for the HAP-NodeJS server (e.g. start with "DEBUG=* node Core.js" to see full output. Maybe it exits on a specific execution point?

**Comment by Bensk1** [comment]
Same problem here with Raspberry, but TP-Link router. There was nothing in the logs. The devices come even back after a while in the HMCatalog app. It might be a raspberry problem. I was running a web server on my raspberry for around year. From time to time it was not reachable for a couple of minutes.

**Comment by futuretec** [comment]
@sjschneider @Bensk1 
- How do you startup the HAP-NodeJS server? (I use "forever" which is started via a cronjob on boot)
- Which network interface do you use with the RPi? (USB WiFi or built-in Ethernet port)

**Comment by Bensk1** [comment]
I used a startup script which simply executes something like 
`node app.js...`

I am also using USB WiFi. But if I remember correctly it is not a general network problem. SSH connections work even when the devices are not reachable.

**Comment by sjschneider** [comment]
@futuretec I've encountered the problem running with BridgedCore.js using both node and forever.  I was using the USB WiFi, but I just moved it to use the built-in ethernet with a different router and no success.  I'll run the code with the DEBUG flag when I get a chance and report back.

@Bensk1 I have not seen the devices come back after they go gray.

**Comment by sjschneider** [comment]
@futuretec Perhaps this is related, but I can repeatably cause the accessories to gray out by turning off my iPhone and turning it back on and trying to use the HMCatalog app again.  At this point, the only way for me to re-enable the accessories is to clear the persist folder, do a 'forever restartall' (or restart it on the command line--I tried both ways), quit the HMCatalog app, and reset the HomeKit configuration settings on my iPhone.  I did this three times.

I am attaching the console output with my insertions for where I turned my phone on and off.  No timestamps, but it all took place over ~2 minutes or so.

<pre>
[---everything initially seems fine, test toggling accessory state---]

  EventedHTTPServer [10.168.2.241] HTTP request: /characteristics +1s
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +3ms
  Accessory [Node Bridge] Processing characteristic set: {"characteristics":[{"aid":2,"iid":10,"value":1}]} +6ms
  Accessory [Node Bridge] Setting Characteristic "BlaBla" to value 1 +3ms
  EventedHTTPServer [10.168.2.241] Muting event '2.10' notification for this connection since it originated here. +39ms
  EventedHTTPServer [10.168.2.241] HTTP Repsonse is finished +16ms
  EventedHTTPServer [10.168.2.241] HTTP request: /characteristics +655ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +3ms
  Accessory [Node Bridge] Processing characteristic set: {"characteristics":[{"aid":2,"iid":10,"value":0}]} +6ms
  Accessory [Node Bridge] Setting Characteristic "BlaBla" to value 0 +3ms
  EventedHTTPServer [10.168.2.241] Muting event '2.10' notification for this connection since it originated here. +49ms
  EventedHTTPServer [10.168.2.241] HTTP Repsonse is finished +5ms

[---Turn iPhone Off---]

  EventedHTTPServer [10.168.2.241] Client connection closed +16s
  EventedHTTPServer [10.168.2.241] HTTP connection was closed +13ms
  EventedHTTPServer [10.168.2.241] HTTP server was closed +5ms

[---Turn iPhone On and open HMCatalog app---]

  EventedHTTPServer [10.168.2.241] New connection from client +56s
  EventedHTTPServer [10.168.2.241] HTTP server listening on port 54826 +5ms
  EventedHTTPServer [10.168.2.241] HTTP request: /pair-verify +20ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: POST /pair-verify +4ms
  HAPServer [CC:22:3D:E3:CE:F6] Pair verify step 1/2 +7ms
  EventedHTTPServer [10.168.2.241] HTTP Repsonse is finished +66ms
  EventedHTTPServer [10.168.2.241] HTTP request: /pair-verify +14ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: POST /pair-verify +4ms
  HAPServer [CC:22:3D:E3:CE:F6] Pair verify step 2/2 +6ms
  HAPServer [CC:22:3D:E3:CE:F6] Client 6CE9CBB9-9614-48F9-B461-38BDFCA10DC8 verification complete +22ms
  EventedHTTPServer [10.168.2.241] HTTP Repsonse is finished +12ms
  EventedHTTPServer [10.168.2.241] HTTP request: /accessories +20ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: GET /accessories +3ms
  EventedHTTPServer [10.168.2.241] HTTP Repsonse is finished +21ms

[---All HMCatalog accessories are disabled, nothing further happens here---]
</pre>

**Comment by BerndDA** [comment]
@sjschneider I had exactly the same console output after adding a new accessory type. It took me a while to figure out why all the accessories greyed out after restart or after the phone was out of the local network for a while.
In the end it was a characteristic that returned "undefined" when queried due to a bug.
After solving the issue, everything works fine again.
Hope this helps.

**Comment by straccio** [comment]
I have the same issue, could be the homekit home sharing feature? I have seen this happen after have invited my wife iCloud account.

**Comment by sjschneider** [comment]
@Berndda I was using the Garage Door Opener Accessory and removing the "undefined" responses resolved the problem!

**Comment by Marat86K** [comment]
Hello!
I have the same problem. @KhaosT Could you explain how I should modify GarageDoorOpener_Accessory.js?
I have deleted this  `callback(undefined)`, but after 20 minutes it becomes gray.

`      onRead: function(callback) {
        console.log("Read:");
        execute("Garage Door - obstruction detected", "Current State", null);
        callback(undefined); // only testing, we have no physical device to read from`

Sorry for disturbance!

**Comment by KhaosT** [comment]
@Marat86K I'd suggest you to move to the new accessory model (check lock accessory). If you just want to get that one work, you can try to invoke callback with [defined value](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L444).

```
callback(0);
```

**Comment by Marat86K** [comment]
@KhaosT thank you very much for prompt reply, but the problem occurs again. It works fine and then dosn`t detected by iOS. I try change router from TimeCapsule to Zyxel, maybe with IP i don`t use static or with GarageDoorOpener_Accessory.js?

**Comment by KhaosT** [comment]
@Marat86K If it disappears, then it's more likely that HomeKit doesn't like the data accessory returned. make sure you changed all of them https://github.com/KhaosT/HAP-NodeJS/blob/master/accessories/GarageDoorOpener_accessory.js#L108, L129.

**Comment by Marat86K** [comment]
@KhaosT, thank you again!!! Problem is not solved. I think problem in this 

After command: "sudo forever start"
I saw this:
" warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms"
Where can I adjust spinSlipTime and minUptime???

**Comment by KhaosT** [comment]
@Marat86K if you are using ``forever``, please check their npm page to find out how to change those parameters.
