### ISSUE TITLE
Custom Service + Custom Characteristic

### ISSUE THREAD

**Issue by henzed** [KhaosT/HAP-NodeJS#153]
Hey, 

I just wanted to ask if you plan to add Service.Custom and Characteristic.Custom to the code aswell. I did not want to add a pull request, because it says that the file is generated.
(Currently I'm extending your lib by these functions)

Characteristic.Custom = function() {
    Characteristic.call(this, 'Custom', '9372E03B-69B2-43D5-80B7-7E3996CC9A4A');
    this.value = this.getDefaultValue();
};

inherits(Characteristic.Custom, Characteristic);

Service.Custom = function (displayName, subtype) {
    Service.call(this, displayName, '5408E8EC-7B41-4371-935C-BE5C3053C06C', subtype);
};

inherits(Service.Custom, Service);

**Comment by KhaosT** [comment]
What's the purpose of this "custom" service/characteristic?

Ideally if none of the pre-defined service fits the developer's need, they have the freedom to define any service/characteristic on their own. Since HomeKit apps will use service type/characteristic type to figure out what user can control, defining a specific "custom" service/characteristic without restricting behavior feels dangerous to me.

**Comment by henzed** [comment]
It's actually one of the given services / characteristics types in the HomeKit Accessory Simulator, therefore i would have added it

**Comment by KhaosT** [comment]
@henzed the "custom" service/characteristic generates a random UUID every time you created it, it's not a const.
