### ISSUE TITLE
Siri: Sorry, that is not supported

### ISSUE THREAD

**Issue by leoneleone** [KhaosT/HAP-NodeJS#247]
I'm modifying the homebridge-sensibo plugin since things aren't working as perfectly ever since iOS 9.3.2
Everything worked fine under 9.3.1 

The problem: 
when I ask Siri to "turn on the thermostat", I get the response "sorry, that is not supported"

I've added (Characteristic.On) to the Thermostat Service:

	this.getService(Service.Thermostat)
		.addCharacteristic(Characteristic.On)
		.on('get', function(callback) {
			if (that.state.on=true)
				callback(null, true);
			else
				callback(null, false); 	
		})
		.on('set', function(value, callback) {
			callback();
			if (value) {
				that.state.on=true;
			} else {
				that.state.on=false;
			}
			that.platform.api.submitState(that.deviceid, that.state);
		})

This used to work perfectly before updating to iOS 9.3.2 and the latest version of homebridge. 

@KhaosT :  Any idea what has changed regarding HomeKit and/or homebridge/HAP-NodeJS that is causing this issue? 
Is this a bug with Siri? The same Siri command used to work. Or has Siri/HomeKit become more strict about what additional characteristics you can add to Service.Thermostat?

**Comment by KhaosT** [comment]
I think it's a hard coded case on Siri server side to workaround the situation that HomeKit doesn't support changing thermostat's target state. Unfortunately, since it's hard coded to tell you it's not supported command when you try to do anything related to changing thermostat's state, it also breaks your workaround … not really sure this can be fixed from accessory side.

**Comment by leoneleone** [comment]
Yes, I realise HomeKit server side keeps on changing regarding Siri Commands. Funnily enough, turning the thermostat On and Off still works when using an app

**Comment by dodekeract** [comment]
A quite dirty workaround would be possible, if you just add a "light" that's called thermostat.

**Comment by leoneleone** [comment]
@dodekeract:  I'd like the Thermostat to show up as just one Accessory in HomeKit

How would your "dirty" workaround be implemented in code? 😊

**Comment by dodekeract** [comment]
@leoneleone Basically by making a completely separate second accessory, which only supports on/off. As I said, it's not really the best way - but if this is truly Siri's fault, it may be the only one.

**Comment by sekizinci** [comment]
Hi, I am wondering I am not a master in IoT but I have a Pi3 and I have integrated with homekit and openhab2, but when I send a command via siri still I receive same answer in that case also basically I am trying to on/off a light with basic python code. In home kit when I press the on off button led is working but when I send a command via siri it says does not support. My IOS is 10.2. May I use Siri with these versions or it is not possible. Because I saw lots of videos somebody makes these futures but i can not see any version info.
