### ISSUE TITLE
iOS 10 - Notification only for Lock accessroy 

### ISSUE THREAD

**Issue by rahulmr999** [KhaosT/HAP-NodeJS#254]
Hi,
I was able to integrate with the Apple Home app which is available in iOS 10 beta and it works !!!. 
But I am not sure why I get a notification when I change the Lock Status to On/Off and not for other accessories . I tried adding a motion sensor accessory and triggering the MotionDetected. 

I am not able to get the notification like the one that I get for the Lock accessory .
￼
![img_0926](https://cloud.githubusercontent.com/assets/11288855/16138827/11d58ff4-345f-11e6-8709-2f1e366d99f0.PNG)

**Comment by justme-1968** [comment]
thats ok. the lock is the only accessory that will Five this notifikation.

**Comment by rahulmr999** [comment]
Thanks, is that a kind of limitation or so ? I was planning to trigger the notification using a motion sensor.

**Comment by DerEisvogel** [comment]
Hey, as of iOS 9 HomeKit can only send push notifications fro Security Systems, Locks, Electric Doors and Windows. They might have changed that in iOS 10. You can check in your system settings:
Notifications -> HomeKit -> Bottom switches.

I really don't see why Apple has limited notifications in that way, because it might be useful to have a notification when you are away and the smoke alarm goes off.

**Comment by leoneleone** [comment]
I have a Schlage Sense lock and I don't get any HomeKit notifications even though my iPhone is setup to receive them. I have no ideas why!! I'd like to get the notifications of course.

**Comment by KhaosT** [comment]
Current iOS only supports sending notification for a small collection of services/characteristics (mostly security related.)

@leoneleone for Bluetooth LE accessory like Schlage, it will need a firmware update to show notification. Please contact Schlage for more details.
