### ISSUE TITLE
On normal set request a number, with Siri a boolean

### ISSUE THREAD

**Issue by TheNoim** [KhaosT/HAP-NodeJS#287]
Hello Guys,
I found a bug. If you register the set request, you get two types of values.
What i try to say, if you switch as example a Light normal over the HomeKit APP from Apple, you get as new Value a 0 or 1. But if you try to switch a state with Siri, you get true or false. First I did not knew that, this is why I wonderd, why my code only worked with the normal HomeKit App. But the i printed the Status, if i make a request, and know, it works.
How i did it:
http://pastebin.com/A0rBk9xT (I don't know how to format it right here on the issue tracker)
I added to my switch, true or false. Maybe, this is a TODO for the Projekt, that you will only get one type. I hope you can understand me, because this is very broken english :D
Best regards Nils

**Comment by KhaosT** [comment]
Hi Nils,
Currently hap-nodejs just forward what iOS sent to accessory to characteristic, depends on the application you use on iOS, it may decide to send different things. The ``bool`` situation is a little tricky with HomeKit since it thinks both "0"/"1" or "true"/"false" is fine... At this stage I think it's up to developer to handle the problem instead of me doing conversion at a lower level.
