### ISSUE TITLE
a rather bizarre issue

### ISSUE THREAD

**Issue by mrose17** [KhaosT/HAP-NodeJS#371]
@KhaosT - i suspect that the root cause is "pilot error" on my part, but after repeated "forays into the breech", i'm not seeing what i'm doing wrong. can you provide a pointer? also, sorry for the amount of context necessary to explain the issue.

the https://github.com/homespun/homespun-discovery repo is required by some of my homebridge plugins -- e.g.. https://github.com/homespun/homebridge-platform-aqe -- that  use an `engine` of  `"homebridge": ">=0.4.16"` -- https://github.com/homespun/homebridge-platform-aqe/blob/master/package.json#L15 -- which, in turn requires `"hap-nodejs": "0.4.20"` -- https://github.com/nfarina/homebridge/blob/master/package.json#L29 -- in other words, it's all "the latest".

so, we have an air-quality egg reporting NO2 and O3 via MQTT to homebridge, and on the first publish, we have the code invoked at https://github.com/homespun/homespun-discovery/blob/master/utilities/utility-pushsensor.js#L56 with `self.capabilities` set to

          { no2         : { ... }
          , o3          : { ... }
          , humidity    : { ... }
          , temperature : { ... }
          }

this results in each of the four capabilities being traversed and the services for the accessory being created, initialized, etc. this all worked fine, until i added the block at https://github.com/homespun/homespun-discovery/blob/master/utilities/utility-pushsensor.js#L185 to create/modify `Service.AirQualitySensor` -- which blows up at https://github.com/homespun/homespun-discovery/blob/master/utilities/utility-pushsensor.js#L187 because the service does not have a `Characteristic.OzoneDensity`. 

in looking at the service that is returned, it has two characteristics, `Characteristic.Name` and `Characteristic.NitrogenDioxideDensity` which gets filled in at https://github.com/homespun/homespun-discovery/blob/master/utilities/utility-pushsensor.js#L169

whew, that's the context. so... what happened to all the other characteristics in `Service.AirQualitySensor` ... how did i delete them accidentally?

many thanks!

**Comment by mrose17** [comment]
@KhaosT - any suggestions? i am stuck... thanks!

**Comment by KhaosT** [comment]
``Characteristic.OzoneDensity`` is an optional characteristic for service ``Service.AirQualitySensor``. This shouldn't be a problem if you're just using HAP-NodeJS. However, if you are using this with homebridge along with the accessory caching mechanism, the optional characteristics will not be populated after accessory being added to homebridge (aka if you add the accessory to homebridge, restart homebridge, the accessory you get in configureAccessory will not having optional characteristics.) So if you are doing the following:
1. add AirQualitySensor service to accessory and invoke get NitrogenDioxideDensity characteristic on the service
2. add the accessory to homebridge
3. reboot homebridge
4. trying to invoke get OzoneDensity characteristic from the AirQualitySensor, it will say the characteristic doesn't exist because it's not in optional characteristics anymore.

Can you confirm that step 3 is occurred when you encountered this problem?

**Comment by mrose17** [comment]
there's no reboot. i think the sequence is more like:

    service = new Service.AirQualitySensor()
    service.setCharacteristic(Characteristic.Name, self.name + ' Air Quality')
    service.getCharacteristic(Characteristic.NitrogenDioxideDensity)
           .on('get', function (callback) { self._getState.bind(self)(key, callback) })
    accessory.addService(service, self.name)
    ...
    service = accessory.getService(Service.AirQualitySensor)
    service.setCharacteristic(Characteristic.Name, self.name + ' Air Quality')
    service.getCharacteristic(Characteristic.OzoneDensity)
           .on('get', function (callback) { self._getState.bind(self)(key, callback) })

so my guess is that the `accessory.addService` is what's stripping out the optional characteristics.

i'm going to refactor something on my end to see if i can defer that one call to the end... i'll let you know how it goes!

**Comment by KhaosT** [comment]
``accessory.addService`` should not touch your optional characteristics... Can you print out ``service.optionalCharacteristics``?

**Comment by mrose17** [comment]
it's empty. see attached
[service.txt](https://github.com/KhaosT/HAP-NodeJS/files/695349/service.txt)

**Comment by KhaosT** [comment]
Interesting... I'm not sure why then, that array should not be empty when you first create the service.

**Comment by mrose17** [comment]
hmmm.... i think that you're right that it's coming through the configureAccessory path... (i missed that log entry).

is there a way to re-invigorate the service? or should i do a `removeService` first?

sorry for my confusion...

**Comment by KhaosT** [comment]
Once the accessory being added, you cannot re-populate optional services. If you really want to modified an existing service, try create characteristic from constructor directly and then add it to service. After doing that, invoke [``updatePlatformAccessories``](https://github.com/nfarina/homebridge/blob/master/lib/api.js#L158).

**Comment by mrose17** [comment]
that did the trick. can you do me a favor and advise me on one more thing: should `registerPlatformAccessories` be called only after one or more accessories have been created? it looks like my code always calls it regardless of whether the accessory is new or being handled via `configureAccessory` ... thanks!

**Comment by KhaosT** [comment]
``registerPlatformAccessories`` should only be called when plugin creates new accessories. You should only invoke that function with newly created accessories (instead of including old, existing accessories). Don't invoke ``registerPlatformAccessories`` for accessories you received in ``configureAccessory``, those are already in homebridge's database and invoking ``registerPlatformAccessories`` may result unexpected behavior.

**Comment by mrose17** [comment]
thanks! i haven't seen anything odd, but i'll update my code...
