### ISSUE TITLE
Temperature sensor not working in Apple homekit automation

### ISSUE THREAD

**Issue by KevinBeckers** [KhaosT/HAP-NodeJS#375]
Hi,

Is it possible to enable te temprature sensor in homekit automation?
The default temprature sensor seems not reconised as an automation sensor.
I also tested the motion sensor and that works fine.

Thx

**Comment by KhaosT** [comment]
I think Home app doesn’t support numerical value based automation. Please try use third party app like Eve or Hesperus to create automation.

Best Wishes,
Tian

**Comment by KevinBeckers** [comment]
Thank you for the quick response.
You are right. Eve works fine!

**Comment by abhimanyuyadav** [comment]
Except, that Eve works only over Bluetooth :( So if you plan on using a home hub like an AppleTV, it needs to be in BT range

**Comment by TLCary** [comment]
The temperature sensor is greyed out in the Home app. Since it's inactive it doesn't show up in automation.  I've set the StatusActive characteristic, and in the Home app under Details for the temperature sensor a line for Status Active Yes appears but the icon is stilled greyed.   The Sensor doesn't have a Active characteristic.   It seems like it should, or Status Active should make it active.  Hue provides an Enabled characteristic, but that isn't present either.  What am I missing?

**Comment by rikray02** [comment]
Today, i expect the same problem with my sonoff TH16.  I use MQTT and a good pluggin.  I see the temperature in Homekit but i can't use this information to do an automation.  Does it an apple problem (temperature sensor not supported with HomeKit) or i have misconfigured somethings in my iPhone?

Thanks for your suggest!
Richard
