### ISSUE TITLE
Status of Accessories

### ISSUE THREAD

**Issue by amz4u2nv** [KhaosT/HAP-NodeJS#41]
Hi,
Really like the project, but I sometimes have an issue, where siri states that it cannot perform the action at the moment. However, when I say to turn off the accessory before turning it on then it seems to work.
My question is does it know the state of the device hence it has to be turned off?

Thanks

**Comment by KhaosT** [comment]
Siri should keep tracking the status of accessories but that's not why you encountered the issue. Siri will say "cannot perform the action" when:
1. Connection to accessory timed out
2. Accessory is not reachable
3. Internal error (rarely)

For the issue you encountered, I guess it's either caused by (1) or (2).
