### ISSUE TITLE
Multiple Light Accessories?

### ISSUE THREAD

**Issue by rivaanbechan** [KhaosT/HAP-NodeJS#429]
I'm trying to figure out how to add multiple light accessories. Although I can't seem to find any examples that I can work with. Does anyone have an example project for me to use?

**Comment by snowdd1** [comment]
You might be better off with `homebridge` which is a plugin framework on top of `HAP-NodeJS`.  

If you want to stay with HAP-NodeJS, you can put multiple accessories into an array and return that by a JavaScript file that ends with [`_accfactory.js` instead of `_accessory.js`](https://github.com/KhaosT/HAP-NodeJS/blob/v0.4.22/lib/AccessoryLoader.js#L31-L37). Ages ago I used that for my platform, but later decided that homebridge is the more comfortable way to go - plus there are hundreds of other plugins already available.

The last version of the factory example was [that](https://github.com/KhaosT/HAP-NodeJS/blob/v0.0.2/accessories/KNX_Dimmers_accfactory.js.sample.js) in tag version 0.0.2. It's deprecated long since, but the last three lines of code might still work - pushing prepared accessories into an array and return that array.

**Comment by MarioMP1993** [comment]
Como puedo añadir mas accesorios a homebridge?

gracias

**Comment by rivaanbechan** [comment]
Thank you :) Homebridge it is! 👍
