### ISSUE TITLE
How to tell HomeKit reachable status of bridge

### ISSUE THREAD

**Issue by yene** [KhaosT/HAP-NodeJS#499]
Hi,

my bridge represents another network device. If that device is down, I would like to inform HomeKit that it is not yet ready.

I saw that the bridge has a reachable characteristics, is this still in use, or deprecated?

**Comment by washcroft** [comment]
Accessories can expose a BridgingState service which can tell HomeKit the "Reachability" of the accessory via the characteristic of the same name. 

This service was included by default with every platform accessory until it was removed in v0.4.26 (445b3408484315be9b5573e552b1b2a899fcda2b).

You can still add the service, I'm not sure why it was removed. It was mentioned in #408 that Apple had removed the service in iOS 10.2, however I do not believe this because the Home app even in iOS 11 still shows that the accessory isn't reachable when this characteristic is set to false which is a handy status/feature to be able to set.

The service isn't mentioned in the non-commercial public HomeKit documentation, but I suspect it does exist for commercial users.

**Comment by NorthernMan54** [comment]
On a side note related to this, if in response to a get or set characteristic request you return an error, the accessory is marked as unreachable.

**Comment by washcroft** [comment]
This is probably the preferred method, since it locks out the UI when the "get" characteristic returns an error.

**Reachability = false**

![img_2401](https://user-images.githubusercontent.com/1866176/31430172-fe00bef2-ae67-11e7-8b15-4bb34d07fa0e.PNG)

![img_2398](https://user-images.githubusercontent.com/1866176/31430173-fe17e924-ae67-11e7-8bb7-634a4171488e.PNG)

**Error on "get" characteristic**
![img_2400](https://user-images.githubusercontent.com/1866176/31430175-fe41f098-ae67-11e7-8d3e-c68335e55f9c.PNG)


![img_2399](https://user-images.githubusercontent.com/1866176/31430174-fe2d486e-ae67-11e7-82a5-df2a1d879455.PNG)

**Comment by yene** [comment]
I agree, I think apple realized that there is no point in unreachable, your bridge is configured and works, or doesn't.

**Comment by NorthernMan54** [comment]
I’m thinking it’s a deprecated function, and will be removed with a future release.  I was using this feature, and have now switched to using the error function on get/set.  What I find missing is the ability to force the status, you need to wait for a get/set event then you can set the status.   And if your device doesn’t support get/set, then you can’t set the status.

I tried using events, but events don’t seem to support error status.  Have you seen anything?

**Comment by plasticrake** [comment]
I'm also trying to figure out the best way to report the "reachability" of my accessories since Homebridge removed this.  I notice some projects use `Characteristic.StatusFault`, I was going to look into how that behaves.

**Comment by NorthernMan54** [comment]
I had looked at status fault, and if I recall correctly it set an indicator only visible from the device details screen.  But I did find that low battery was visible from the status screen, so I used low battery to indicate a sensor fault.  This would show up on the home screen.
