### ISSUE TITLE
Default setProps maxValue for NO2, SO2, O3, VOC, PM2.5, and PM10

### ISSUE THREAD

**Issue by deanlyoung** [KhaosT/HAP-NodeJS#609]
Curious why these all have default = 1000, whereas CO₂, for example, has 100,000?

Bonus: temperature minValue only goes down to 0 (i.e. freezing)

**Comment by Supereg** [comment]
These min/max values are all defined by Apple in the HomeKit accessory protocol (HAP). So because these values are in the specification.
You probably need to ask Apple if you want to have an answer 😅 

However you can change these values for example for the temperature characteristic. Don't know how this works in HAP-NodeJS however.

**Comment by deanlyoung** [comment]
@Supereg interesting. I know Eve Room, for example, reports values higher than 1000, so was curious why these seem limited. Will try to override them in my own plugin.

**Comment by KhaosT** [comment]
Yeah those are default values from the simulator. Please override it on individual characteristics to fit your needs :)
