### ISSUE TITLE
How to make Characteristic.PositionState perms include write？

### ISSUE THREAD

**Issue by songzh96** [KhaosT/HAP-NodeJS#613]
I want make  WindowCovering have 3 buttons,it's open stop and close.How can I achieve it?

**Comment by Supereg** [comment]
I think you don’t quite understand how the WindowCovering works. The „PositionState“ is only used to let the controller know what the window covering is current „doing“ (opening, closing, stopped). By writing to the TargetPosition Characteristic you tell the covering what to do, since the cover must know his CurrentPosition as of HAP specs.

If you just need three buttons simply add three switches 🤷🏽‍♂️

**Comment by songzh96** [comment]
Thank you for your answer, I know what you mean, but currently in China, we tend to use the button to control the curtains.a button include "open" "close" and "stop".
In fact, what I want to know more is whether I can modify the attribute value of the accessory.

**Comment by songzh96** [comment]
> I think you don’t quite understand how the WindowCovering works. The „PositionState“ is only used to let the controller know what the window covering is current „doing“ (opening, closing, stopped). By writing to the TargetPosition Characteristic you tell the covering what to do, since the cover must know his CurrentPosition as of HAP specs.
> 
> If you just need three buttons simply add three switches 🤷🏽‍♂️
Thank you for your answer, I know what you mean, but currently in China, we tend to use the button to control the curtains.a button include "open" "close" and "stop".
In fact, what I want to know more is whether I can modify the attribute value of the accessory.
