### ISSUE TITLE
Questions about WindowCovering

### ISSUE THREAD

**Issue by songzh96** [KhaosT/HAP-NodeJS#619]
Why WindowCovering.PositionState haven‘t  “closed” and “opened” in HAP。

But I found "opened" and "closed" in my home app windowCovering Accessories.

If I want to add it.how do I do.

Another question：
 I found AirPurifier characteristic include FilterChangeIndication。Is this a hidden characteristic? 
 Is it the case with other accessories?

respect

**Comment by Supereg** [comment]
Simply because WindowCovering isn’t designed like that. PositionState only gives information about what the covering is currently „doing“: opening, closing or stopped.

The state itself is determined using the CurrentPosition and TargetPosition characteristics. When both are at 0% covering is closed, when both are at 100 covering is open (provided PositionState is „stopped“).

Have a look at the HAP non-commercial specifications. There is everything explained a bit more detailed.

**Comment by songzh96** [comment]
> HAP

Thank you very much for your answer.

**Comment by songzh96** [comment]
> Simply because WindowCovering isn’t designed like that. PositionState only gives information about what the covering is currently „doing“: opening, closing or stopped.
> 
> The state itself is determined using the CurrentPosition and TargetPosition characteristics. When both are at 0% covering is closed, when both are at 100 covering is open (provided PositionState is „stopped“).
> 
> Have a look at the HAP non-commercial specifications. There is everything explained a bit more detailed.

Thank you very much for your answer.
