### ISSUE TITLE
tsc --build tsconfig.json fails

### ISSUE THREAD

**Issue by ilendemli** [KhaosT/HAP-NodeJS#734]
I tried to compile using tsc because the project runs awfully slow on a Raspberry Pi Zero W since the TypeScript merge but it fails with the following error:

```
pi@raspberrypi:~/HAP-NodeJS $  tsc --build tsconfig.json
src/lib/gen/importAsClasses.ts:182:9 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'typeof Formats'.
  No index signature with a parameter of type 'string' was found on type 'typeof Formats'.

182     if (Formats[key] == format)
            ~~~~~~~~~~~~

src/lib/gen/importAsClasses.ts:191:9 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'typeof Units'.
  No index signature with a parameter of type 'string' was found on type 'typeof Units'.

191     if (Units[key] == units)
            ~~~~~~~~~~


Found 2 errors.
```

**Comment by Shaquu** [comment]
Well it looks like you have some rules in tsconfig.json that cause an error and maybe it is not important for the whole project to work properly?

Can you share what is inside of yours tsconfig.json?

**Comment by ilendemli** [comment]
@Shaquu it's the same [tsconfig.json](https://github.com/KhaosT/HAP-NodeJS/blob/master/tsconfig.json) one as in this project, running it with ts-node is no problem, it just takes ages to start and parse accessories.
I wanted to compile and try it that way but encountered that error.

**Comment by gkaindl** [comment]
The problem is that the both ```Formats``` and ```Units``` are enums with string values now, and TypeScript complains about accessing the values directly with string keys.

You can change the offending lines to

```if (Formats[key as keyof typeof Formats] == format)```

and

```if (Units[key as keyof typeof Units] == units)```

to fix this.

I'm unsure if someone should make a pull request for a fix like this: The offendign file is in the ```/gen``` subdirectory, which sounds like it's being generated from something, but I can't find the the script generating ```importAsClasses.ts```. It would make more sense to fix it there, rather than in the generated code.
