### ISSUE TITLE
Ability to catch 'EADDRINUSE'

### ISSUE THREAD

**Issue by marcus-j-davies** [KhaosT/HAP-NodeJS#792]
Hello,

Thanks to all those involved in the development of this project.
it's opened up so many possibilities. So thank you.

Is there a way, I can catch 'EADDRINUSE' in eventedhttp.js?

 ```
 listen = (targetPort: number) => {
    this._tcpServer.listen(targetPort);

    this._tcpServer.on('listening', () => {
      const address = this._tcpServer.address();

      if (address && typeof address !== 'string') {
        var port = address.port;
        debug("Server listening on port %s", port);
        this.emit(EventedHTTPServerEvents.LISTENING, port);
      }

    });
```
 
I have created a collections of nodes for node-red, that represent various pre-configured 'ready to use' devices (Camera,TV, Alarm,Garage Door Opener,...). the approach is non bridged.

Whilst most users will know to adjust the unique values (namely the port), I would like to catch this situation if possible.

Attempting to try/catch on **publish** the EADDRINUSE did not bubble up for me.

My current work around, and one that is a little.... cheap. is to ensure the user has at least reviewed the configuration for the device.

This still does not guarantee  the port they have specified is free, and being able to catch 'EADDRINUSE' will allow a more user friendly approach to dealing with it, instead of crashing Node-Red enitrely.

Thanks

**Comment by ebaauw** [comment]
You can catch (otherwise) uncaught exceptions through `process.on('unCaughtException', ...)`, but that will be too late to do anything useful other than shutting down gracefully.  I did a PR implementing this for homebridge so plugins can shutdown gracefully when homebridge or one of the (other) plugins would crash: https://github.com/nfarina/homebridge/blob/fad984cd36c6f22178a71862bf53ec95a94f2859/lib/cli.js#L52

Typically instances of `events.EventEmitter` and its subtypes don't throw errors, but emit `error` events.  To catch the EADDRINUSE, you'd need to install a handler for the `error` event, `this._tcpService.on('error', (error) => { ... })`.

**Comment by marcus-j-davies** [comment]
Thanks ebaauw,

Given a typical accessory js file, would I be able to get a handle on the tcp object, and therefore install my handler?, or is the (several layers deep) tcp object out of reach?

**Comment by ebaauw** [comment]
I suppose technically you could do a `accessory._server._httpServer._tcpServer.on('error', ...)`, but properties and methods starting with `_` are supposed to be private, and shouldn't be accessed outside the HAP-NodeJS code.

I think the proper way would be a PR on HAP-NodeJS.  Still, I think there's little more one could do in `eventhttpd.js`, other than changing the error message into something more user friendly and quitting.  If you want to do something more useful, like trying another port, you'd have to propagate the `error` event through the chain, just like e.g. the `listening` event.

**Comment by marcus-j-davies** [comment]
Yup.

I'm still learning the world of NodeJS ( I come from a .Net background)
Thanks for your help, I'll explore `unCaughtException`.
