### ISSUE TITLE
Can't add the same accessories to multiple iOS devices

### ISSUE THREAD

**Issue by nfarina** [KhaosT/HAP-NodeJS#80]
This hasn't been a problem in the past but now seems to be very consistent. When I add an accessory to my personal iPhone, it works fine but I can no longer add that same accessory to my wife's iPhone.

To reproduce:

 - Bring up the "Add accessory" screen on two iOS devices
 - Add the accessory on device one, success
 - Accessory immediately disappears (!) from the "Add accessory" screen on device two

**Comment by snowdd1** [comment]
That's not a bug but a feature. iOS 9 beta 1 requires the devices to pair with only one iCloud account. If you want to share your home use the home sharing feature of your home kit app.

**Comment by nfarina** [comment]
Ah, didn't know that. And I suppose you need iOS 9 in order to do the sharing itself in the first place? We're both running iOS 8 right now—so guessing this was a HAP-NodeJS change?

**Comment by nfarina** [comment]
OK I'm guessing the iOS 9 "fix" commit (19a4bee7d82674ac0051706687def1e3570c2b68) was a matter of adding the per-device restriction?

**Comment by nfarina** [comment]
Yep, it's described in #69. OK closing this!

**Comment by snowdd1** [comment]
I am using MyTouchHome as home kit app, and though it is not overwhelming in functionality it gives the possibility to add users to my home. I was able to add my wife by adding her appleId in the user list. She received an invitation even without having an home kit app installed, it's part of IOS since 8.x. She can use Siri to control the lights without having an home kit app on her device after accepting the invitation.

**Comment by nfarina** [comment]
Oh that is great to know! I'll definitely do that. I hadn't seen that part of MyTouchHome as it doesn't appear for me for some reason. I think I need to recreate my home.

**Comment by snowdd1** [comment]
It only shows on the device on which you created the home. I have an iPad and an iPhone on the same iCloud account and I can manage the home on the iPad only.

**Comment by nfarina** [comment]
I had to delete my old "Home" and recreate it - there must be some legacy status associated with the old one. But now MyTouchHome lets me invite people and I successfully invited my wife. She can see all my accessories and everything works great!

**Comment by rooi** [comment]
I'm glad I found this issue since I was having the same problem with connecting multiple devices. Sharing through iCloud does work, which is nice. There is one problem, the room and zone names cannot be changed on the invited device and we're using different languages. Is this an apple oversight or am I missing something?

Thanks!
